"" _vimrc
"" michael@mwild.me

" include the system vimrc
source $VIM/_vimrc

" use the windows clipboard
set clipboard=unnamed

" behave mswin causes issues - this works as expected
behave xterm

" tabs as 4 spaces
set tabstop=8 
set softtabstop=0 
set expandtab 
set shiftwidth=4 
set smarttab

" indent sanely
set autoindent

" put backups in temp
set backupdir=~/AppData/Local/Temp
set dir=~/AppData/Local/Temp
